name: E2E Tests

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [edge]
    paths-ignore: ["**.md"]

  pull_request:
    paths-ignore: ["**.md"]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.test.yml
          compose-flags: "--env-file test.env"
      - uses: cypress-io/github-action@v5
        with:
          config: baseUrl=http://localhost
          spec: cypress/e2e/!(third-party)/**/*.cy.js
          working-directory: e2e
